# Black Myth Wukong Benchmark Configuration
metadata:
  game_name: "Black Myth Wukong"
  path: "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Black Myth Wukong Benchmark Tool\\b1\\Binaries\\Win64\\b1-Win64-Shipping.exe"
  process_id: "b1"  # Actual process name in Task Manager
  version: "1.0"
  benchmark_duration: 150
  startup_wait: 30
  resolution: "1920x1080"
  preset: "High"

# Simple step-by-step workflow
steps:
  1:
    description: "In main menu - Click on options"
    find:
      type: "icon"
      text: "Options"
      text_match: "contains"
    action:
      type: "click"
      button: "left"
      move_duration: 0.5
      click_delay: 0.5
    verify_success:
      - type: "icon"
        text: "Benchmark"
    expected_delay: 10
    timeout: 20

  2:
    description: "Click Benchmark"
    find:
      type: "icon"
      text: "Benchmark"
      text_match: "contains"
    action:
      type: "click"
      button: "left"
      move_duration: 0.5
      click_delay: 0.5
    # No detection as of now just 
    # verify_success:  
    #   - type: "icon"
    #     text: "Toggle UI"
    expected_delay: 5
    timeout: 20

  3:
    description: "Execute main benchmark with performance monitoring"
    action:
      type: "wait"
      duration: 125
      monitor_performance: true
      log_thermal_data: true
    expected_delay: 0
    timeout: 130

  4:
    description: "Wait for benchmark to run"
    action: "wait"
    duration: 150
    timeout: 120

  5:
    description: "Benchmark Result Page"
    find:
      type: "icon"
      text: "Share Results"
      text_match: "contains"
    action:
      type: "key"
      button: "escape"
    expected_delay: 5
    timeout: 20

  6:
    description: "Click escape to exit to main menu"
    find:
      type: "icon"
      text: "Credits"
      text_match: "contains"
    action:
      type: "key"
      key: "escape"
    verify_success:
      - type: "icon"
        text: "Quit To Desktop"
    expected_delay: 10
    timeout: 20

  7:
    description: "Click Anywhere in the screen"
    find:
      type: "icon"
      text: "Ok"
      text_match: "contains"
    action:
      type: "key"
      button: "space"
    expected_delay: 2
    timeout: 20

# Fallback actions
fallbacks:
  general:
    action: "key"
    key: "Escape"
    expected_delay: 1
    max_retries: 3

Click: 2
Key: Escape, Enter

1:
  description: "Click Exit "
  find:
    type: "icon"
    text: "Exit"
    text_match: "contains"
  action:
    type: "click"
    button: "Right"
  verify_success:
    - type: "icon"
      text: "Confirm"
  expected_delay: 5
  timeout: 20

2:
  description: "Click Play "
  find:
    type: "icon"
    text: "Play"
    text_match: "contains"
  action:
    type: "keypress"
    button: "enter"
  verify_success:
    - type: "icon"
      text: "Settings"
  expected_delay: 5
  timeout: 20
3:
  description: "Click Settings "
  find:
    type: "icon"
    text: "Settings"
    text_match: "contains"
  action:
    type: "keypress"
    button: "m"
  verify_success:
    - type: "icon"
      text: "Video"
  expected_delay: 5
  timeout: 20
